{{- if .Values.nats.enabled }}
{{- if not .Values.nats.external }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-nats-streaming
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}