{{- if .Values.kafka.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtrigger-kafka
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    svc: mqtrigger
    messagequeue: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: mqtrigger
      messagequeue: kafka
  template:
    metadata:
      labels:
        svc: mqtrigger
        messagequeue: kafka
    spec:
      securityContext:
      {{ toYaml .Values.kafka.podSecurityContext | indent 6 }}       
      containers:
      - name: mqtrigger
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: ["/fission-bundle"]
        args: ["--mqt", "--routerUrl", "http://router.{{ .Release.Namespace }}"]
        env:
        - name: MESSAGE_QUEUE_TYPE
          value: kafka
        - name: MESSAGE_QUEUE_URL
          value: "{{.Values.kafka.brokers}}"
        - name: MESSAGE_QUEUE_KAFKA_VERSION
          value: "{{.Values.kafka.version}}"
        - name: TRACE_JAEGER_COLLECTOR_ENDPOINT
          value: "{{ .Values.traceCollectorEndpoint }}"
        - name: TRACING_SAMPLING_RATE
          value: {{ .Values.traceSamplingRate | default "0.5" | quote }}
        - name: DEBUG_ENV
          value: {{ .Values.debugEnv | quote }}
        # TLS authentication is TLS with authentication (2 way)
        # More info: https://docs.confluent.io/current/kafka/authentication_ssl.html#ssl-overview
        {{- if .Values.kafka.authentication.tls.enabled }}
        - name: TLS_ENABLED
          value: "true"
        - name: MESSAGE_QUEUE_SECRETS
          value: /etc/fission/secrets        
        volumeMounts:
        - name: kafka-secrets
          mountPath: /etc/fission/secrets
        {{- end }}        
      serviceAccountName: fission-svc
      {{- if .Values.kafka.authentication.tls.enabled }}
      volumes:
      - name: kafka-secrets
        secret:
          secretName: mqtrigger-kafka-secrets
      {{- end }}
      securityContext:
      {{ toYaml .Values.kafka.containerSecurityContext | indent 8 }}       
      resources:
{{ toYaml .Values.kafka.resources | indent 12 }}           
{{- end }}