{{- if .Values.heapster }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    svc: heapster
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: heapster
  template:
    metadata:
      labels:
        svc: heapster
    spec:
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster-amd64:v1.5.0
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: 
        - /heapster
        - --source=kubernetes:https://kubernetes.default
      serviceAccountName: {{ .Release.Namespace }}/fission-svc
      resources:
{{- end }}