{{- if .Values.heapster }}
---
apiVersion: v1
kind: Service
metadata:
  name: heapster
  namespace: kube-system
  labels:
    svc: heapster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: heapster
spec:
  type: ClusterIP 
  ports:
  - port: 80
    targetPort: 8082
    name: tcp-heapster
  selector:
    svc: heapster
{{- end }}