---
# Source: fission-all/templates/mqtrigger/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtrigger-nats-streaming
  labels:
    chart: "fission-all-1.8.1-pre16"
    svc: mqtrigger
    messagequeue: nats-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: mqtrigger
      messagequeue: nats-streaming
  template:
    metadata:
      labels:
        svc: mqtrigger
        messagequeue: nats-streaming
    spec:
      securityContext:
        runAsGroup: 65534
        runAsUser: 65534       
      containers:
      - name: mqtrigger
        image: "index.docker.io/fission/fission-bundle:1.8.0"
        imagePullPolicy: IfNotPresent
        command: ["/fission-bundle"]
        args: ["--mqt", "--routerUrl", "http://router.default"]
        env:
        - name: MESSAGE_QUEUE_TYPE
          value: nats-streaming
        - name: MESSAGE_QUEUE_CLUSTER_ID
          value: fissionMQTrigger
        - name: MESSAGE_QUEUE_QUEUE_GROUP
          value: fission-messageQueueNatsTrigger
        - name: MESSAGE_QUEUE_CLIENT_ID
          value: fission
        - name: MESSAGE_QUEUE_URL
          value: nats://defaultFissionAuthToken@nats-streaming:4222
        - name: TRACE_JAEGER_COLLECTOR_ENDPOINT
          value: ""
        - name: TRACING_SAMPLING_RATE
          value: "0.5"
        - name: DEBUG_ENV
          value: "false"
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true           
        resources:
          {}           
      serviceAccountName: fission-svc
