---
# Source: fission-all/templates/builder/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildermgr
  labels:
    chart: "fission-all-1.8.1-pre16"
    svc: buildermgr
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: buildermgr
  template:
    metadata:
      labels:
        svc: buildermgr
    spec:
      securityContext:
        {}       
      containers:
      - name: buildermgr
        image: "index.docker.io/fission/fission-bundle:1.8.0"
        imagePullPolicy: IfNotPresent
        command: ["/fission-bundle"]
        args: ["--builderMgr", "--storageSvcUrl", "http://storagesvc.default", "--envbuilder-namespace", "fission-builder"]
        env:
        - name: FETCHER_IMAGE
          value: "fission/fetcher:1.8.0"
        - name: FETCHER_IMAGE_PULL_POLICY
          value: "IfNotPresent"
        - name: BUILDER_IMAGE_PULL_POLICY
          value: "IfNotPresent"
        - name: ENABLE_ISTIO
          value: "false"
        - name: TRACE_JAEGER_COLLECTOR_ENDPOINT
          value: ""
        - name: TRACING_SAMPLING_RATE
          value: "0.5"
        - name: FETCHER_MINCPU
          value: "10m"
        - name: FETCHER_MINMEM
          value: "16Mi"
        - name: FETCHER_MAXCPU
          value: ""
        - name: FETCHER_MAXMEM
          value: ""
        - name: DEBUG_ENV
          value: "false"
        securityContext:
          {}           
        resources:
          {}
      serviceAccountName: fission-svc
