apiVersion: v2
name: fission-core
version: 1.8.1-pre5
description: Fission is a fast serverless framework for Kubernetes.
keywords:
- fission
- serverless
home: http://fission.io/
engine: gotpl
appVersion: 1.11.2

sources:
    - https://github.com/fission/fission

maintainers:
    - name: soamvasani
      email: soamvasani+1@gmail.com
      url: https://github.com/soamvasani
    - name: life1347
      email: hello@tachingchen.com
      url: https://github.com/life1347
    - name: funkypenguin
      email: davidy@funkypenguin.co.nz
      url: https://www.funkypenguin.co.nz

dependencies:
  - name: prometheus
    version: 9.3.1
    repository: https://charts.helm.sh/stable
    condition: prometheus.enabled
