apiVersion: apps/v1
kind: Deployment
metadata:
  name: storagesvc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    svc: storagesvc
    application: fission-storage
spec:
  replicas: 1
  strategy:
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      svc: storagesvc
      application: fission-storage
  template:
    metadata:
      labels:
        svc: storagesvc
        application: fission-storage
    spec:
      securityContext:
{{ toYaml .Values.storagesvc.podSecurityContext | indent 8 }}       
      volumes:
      - name: fission-storage
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default "fission-storage-pvc" }}
      {{- else }}
        emptyDir: {}
      {{- end }}      
      containers:
      - name: storagesvc
        image: {{ include "fission-bundleImage" . | quote }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: ["/fission-bundle"]
        {{- if and (.Values.persistence.enabled) (eq (.Values.persistence.storageType | default "local") "s3") }}
        args: ["--storageServicePort", "8000", "--storageType", "s3"]
        {{- else }}
        args: ["--storageServicePort", "8000", "--storageType", "local"]
        {{- end }}
        env:
        - name: TRACE_JAEGER_COLLECTOR_ENDPOINT
          value: "{{ .Values.traceCollectorEndpoint }}"
        - name: TRACING_SAMPLING_RATE
          value: {{ .Values.traceSamplingRate | default "0.5" | quote }}
        - name: PRUNE_INTERVAL
          value: "{{.Values.pruneInterval}}"
        - name: DEBUG_ENV
          value: {{ .Values.debugEnv | quote }}
        volumeMounts:
        - name: fission-storage
          mountPath: /fission
        readinessProbe:
          httpGet:
            path: "/healthz"
            port: 8000
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 8000
          initialDelaySeconds: 35
          periodSeconds: 5
        ports:
          - containerPort: 8000
            name: http
        securityContext:
{{ toYaml .Values.storagesvc.containerSecurityContext | indent 10 }}             
        resources:
{{ toYaml .Values.storagesvc.resources | indent 10 }}           
      serviceAccountName: fission-svc
{{- if .Values.extraCoreComponentPodConfig }}
{{ toYaml .Values.extraCoreComponentPodConfig | indent 6 -}}
{{- end }}
