---
# Source: fission-all/templates/nats/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    svc: nats-streaming
  name: nats-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: nats-streaming
  template:
    metadata:
      labels:
        svc: nats-streaming
    spec:
      securityContext:
        runAsGroup: 65534
        runAsUser: 65534       
      serviceAccount: fission-nats-streaming
      containers:
      - name: nats-streaming
        image: "nats-streaming:alpine"
        imagePullPolicy: IfNotPresent
        args: [
          "--cluster_id", "fissionMQTrigger",
          "--auth", "defaultFissionAuthToken",
          "--max_channels", "0",
          "--http_port", "4223"
        ]
        ports:
        - containerPort: 4222
          protocol: TCP
        - containerPort: 4223
          protocol: TCP
        readinessProbe:
          httpGet:
            path: "/streaming/serverz"
            port: 4223
          initialDelaySeconds: 30
          periodSeconds: 1
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: "/streaming/serverz"
            port: 4223
          initialDelaySeconds: 30
          periodSeconds: 5
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true           
        resources:
          {}
