---
# Source: fission-all/charts/prometheus/templates/alertmanager-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-9.3.1
    heritage: Helm
  name: RELEASE-NAME-prometheus-alertmanager
