---
# Source: fission-all/charts/prometheus/templates/node-exporter-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "node-exporter"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-9.3.1
    heritage: Helm
  name: RELEASE-NAME-prometheus-node-exporter
