---
# Source: fission-all/charts/prometheus/templates/pushgateway-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    component: "pushgateway"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-9.3.1
    heritage: Helm
  name: RELEASE-NAME-prometheus-pushgateway
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-prometheus-pushgateway
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: RELEASE-NAME-prometheus-pushgateway
