---
# Source: fission-all/charts/prometheus/templates/server-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "server"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-9.3.1
    heritage: Helm
  name: RELEASE-NAME-prometheus-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "8Gi"
