{{- if .Values.fluentbit }}
{{- if .Values.logger.podSecurityPolicy.enabled }}
{{- if .Values.createClusterResources }}

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Release.Name }}-fission-logger-privileged
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    svc: logger
spec:
  privileged: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
  {{- if .Values.logger.podSecurityPolicy.additionalCapabilities }}
  allowedCapabilities:
  {{- range .Values.logger.podSecurityPolicy.additionalCapabilities }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}  
{{- end }}