{{- if .Values.fluentbit }}
{{- if .Values.logger.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:{{ .Release.Name }}-fission-logger-privileged
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    svc: logger
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ .Release.Name }}-fission-logger-privileged
{{- end }}  
{{- end }}