{{- if .Values.fluentbit }}
{{- if .Values.logger.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:{{ .Release.Name }}-fission-logger-privileged
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    svc: logger
roleRef:
  kind:     Role
  name:     psp:{{ .Release.Name }}-fission-logger-privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind:      ServiceAccount
  name:      default
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}