---
# Source: fission-all/templates/logger/configmap.yaml
# Fluentbit deployment for Fission
#
# Requires:
# - service account: fission-svc
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-fission-fluentbit
data:
  fluentbit.conf: |
   # Some stuff in this file is copied out of https://github.com/fluent/fluent-bit-kubernetes-logging/blob/master/output/kafka/fluent-bit-configmap.yaml
   [SERVICE]
       Flush 5
       Log_Level info
       Parsers_File parsers.conf
   
   [INPUT]
       Name tail
       Tag log.*
       Path ${LOG_PATH}
       Mem_Buf_Limit 5MB
       Parser docker
       DB /var/log/fission/flb_kube.db
       Skip_Long_Lines   On
       Refresh_Interval  10
   
   [FILTER]
       Name kubernetes
       Match log.*
       Kube_URL https://kubernetes.default.svc.cluster.local:443
   
   #
   # Flatten kubernetes labels so we can tag and query functionuid with influxdb
   #
   [FILTER]
       Name nest
       Match log.*
       Operation lift
       Nested_under kubernetes
       Prefix_with kubernetes_
   
   [FILTER]
       Name nest
       Match log.*
       Operation lift
       Nested_under kubernetes_labels
       Prefix_with kubernetes_labels_
   
   [OUTPUT]
       Name influxdb
       Match log.*
       Host ${INFLUXDB_ADDRESS}
       Port ${INFLUXDB_PORT}
       Database ${INFLUXDB_DBNAME}
       HTTP_User ${INFLUXDB_USERNAME}
       HTTP_Passwd ${INFLUXDB_PASSWD}
       Tag_Keys kubernetes_labels_functionUid
       Sequence_Tag  _seq
   
   
   # Useful for testing config changes
   #[OUTPUT]
   #    Name file
   #    Match log.*
   #    Path /flbout.txt
   

  parsers.conf: |
   [PARSER]
       Name        docker
       Format      json
       Time_Key    time
       Time_Format %Y-%m-%dT%H:%M:%S.%L
       Time_Keep   On
   
       # next bit is useful when the logs from the function itself are in json
       # Command      |  Decoder | Field | Optional Action
       # =============|==================|=================
       #Decode_Field_As   escaped    log
