---
# Source: fission-all/templates/logger/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logger
  labels:
    chart: "fission-all-1.8.1-pre16"
    svc: logger
spec:
  selector:
    matchLabels:
      svc: logger
  template:
    metadata:
      labels:
        svc: logger
    spec:
      securityContext:
        null     
      initContainers:
        - name: init
          image: "busybox"
          imagePullPolicy: IfNotPresent
          command: ['mkdir', '-p', '/var/log/fission']
          volumeMounts:
            - name: container-log
              mountPath: /var/log/
              readOnly: false
      containers:
        - name: logger

          image: "index.docker.io/fission/fission-bundle:1.8.0"

          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          command: ["/fission-bundle"]
          args: ["--logger"]
          volumeMounts:
            - name: container-log
              mountPath: /var/log/
              readOnly: false
            - name: docker-log
              mountPath: /var/lib/docker/containers
              readOnly: true
        - name: fluentbit
          image: "index.docker.io/fluent/fluent-bit:1.0.4"

          imagePullPolicy: IfNotPresent
          # CMD ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
          command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluentbit.conf"]
          env:
            - name: INFLUXDB_ADDRESS
              value: influxdb
            - name: INFLUXDB_PORT
              value: "8086"
            - name: INFLUXDB_DBNAME
              value: "fissionFunctionLog"
            - name: INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: influxdb
                  key: username
            - name: INFLUXDB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: influxdb
                  key: password
            - name: LOG_PATH
              value: /var/log/fission/*.log
          volumeMounts:
            - name: container-log
              mountPath: /var/log/
              readOnly: false
            - name: docker-log
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluentbit-config
              mountPath: /fluent-bit/etc/
              readOnly: true
          resources:
            {}
      serviceAccountName: fission-svc
      volumes:
        - name: container-log
          hostPath:
            path: /var/log/
        - name: docker-log
          hostPath:
            path: /var/lib/docker/containers
        # Fluentbit config location: /fluent-bit/etc/*.conf
        - name: fluentbit-config
          configMap:
            name: RELEASE-NAME-fission-fluentbit
  updateStrategy:
    type: RollingUpdate
