---
# Source: fission-all/templates/storagesvc/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storagesvc
  labels:
    chart: "fission-all-1.8.1-pre16"
    svc: storagesvc
    application: fission-storage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      svc: storagesvc
      application: fission-storage
  template:
    metadata:
      labels:
        svc: storagesvc
        application: fission-storage
    spec:
      securityContext:
        runAsGroup: 65534
        runAsUser: 65534       
      volumes:
      - name: fission-storage
        persistentVolumeClaim:
          claimName: fission-storage-pvc      
      containers:
      - name: storagesvc
        image: "index.docker.io/fission/fission-bundle:1.8.0"
        imagePullPolicy: IfNotPresent
        command: ["/fission-bundle"]
        args: ["--storageServicePort", "8000", "--storageType", "local"]
        env:
        - name: TRACE_JAEGER_COLLECTOR_ENDPOINT
          value: ""
        - name: TRACING_SAMPLING_RATE
          value: "0.5"
        - name: PRUNE_INTERVAL
          value: "60"
        - name: DEBUG_ENV
          value: "false"
        volumeMounts:
        - name: fission-storage
          mountPath: /fission
        readinessProbe:
          httpGet:
            path: "/healthz"
            port: 8000
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 8000
          initialDelaySeconds: 35
          periodSeconds: 5
        ports:
          - containerPort: 8000
            name: http
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true             
        resources:
          {}           
      serviceAccountName: fission-svc
