{{- if .Values.influxdb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    svc: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: influxdb
  template:
    metadata:
      labels:
        svc: influxdb
    spec:
      securityContext:
{{ toYaml .Values.influxdb.podSecurityContext | indent 8 }}       
      containers:
      - name: influxdb
        image: {{ .Values.influxdb.image | quote }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
        - name: INFLUXDB_DB
          value: fissionFunctionLog
        - name: INFLUXDB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: influxdb
              key: username
        - name: INFLUXDB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb
              key: password
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8086
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 30
{{- if.Values.useLivenessProbe }}          
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8086
          initialDelaySeconds: 35
          periodSeconds: 5
{{- end }}              
        securityContext:
{{ toYaml .Values.influxdb.containerSecurityContext | indent 10 }}               
        resources:
{{ toYaml .Values.influxdb.resources | indent 10 }}                   
{{- if .Values.extraCoreComponentPodConfig }}
{{ toYaml .Values.extraCoreComponentPodConfig | indent 6 -}}
{{- end }}
{{- end }}