{{- if .Values.influxdb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    svc: influxdb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  ports:
  - port: 8086
    targetPort: 8086
    name: tcp-influxdb
  selector:
    svc: influxdb
{{- end }}