#
# Fission chart configuration
#

## Image base repository
## Leave it empty for using existing local image
repository: index.docker.io

## Fission image repository
image: fission/fission-bundle

## Image pull policy
pullPolicy: IfNotPresent

## Fission image version
imageTag: 1.8.0

## Set to false if you create the namespaces manually
createNamespace: true

## Namespace in which to run fission functions (this is different from
## the release namespace)
functionNamespace: fission-function

## Namespace in which to run fission builders (this is different from
## the release namespace)
builderNamespace: fission-builder

# When applying updates, Kubernetes defaults to an update strategy of "RollingUpdate"
# However, when RWO storage is involved, this can cause the update to get "stuck", as the
# "old" pod is not terminated until the "new" pod is healthy, but the "new" pod needs the storage
# currently attached to the "old" pod, in order to start. As a result, the "new" pod is never healthy
# The resolution here is to set the strategy to "Recreate", which will first terminate the "old" pod,
# before attempting to start the "new" pod.
updateStrategy: Recreate

# In clusters with multiple fission instances, helm will complain about pre-existing resources
# Set the following to false to avoid (re)creating any cluster-scoped resources.
# It's then up to you to ensure that the necessary clusterresources are created'
createClusterResources: true

# Whether or not to create namespaces for builder/fetcher as part of the helm install
# In some configurations, a service account may have privilegdes to deploy into a namespace, but not
# to create additional namespaces (so the namespaces must be pre-prepared)
createNamespace: true

## Enable istio integration
enableIstio: false

controller:
  ## Kubernetes configuration
  ## For minikube, set this to NodePort, elsewhere use LoadBalancer or ClusterIP.
  serviceType: ClusterIP

  ## Port at which Fission controller service should be exposed when a nodePort service is used
  nodePort: 31313

  ## User can override resource limits/requests below
  resources: {}

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}  

builder:
  ## User can override resource limits/requests below
  resources: {}

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}  

fetcher:
  ## Fetcher repository
  image: fission/fetcher
  ## Fetcher image version
  imageTag: 1.8.0
  
  ## Fetcher is only for to downloading or uploading archive.
  ## Normally, you don't need to change the value here, unless necessary.
  resources:
    cpu:
      requests: "10m"
      ## Low CPU limits will increases the function specialization time.
      limits: ""
    mem:
      requests: "16Mi"
      limits: ""

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}       

kubewatcher:
  ## User can override resource limits/requests below
  resources: {}

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}  

timer:
  ## User can override resource limits/requests below
  resources: {}

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}  

## Logger config
logger:
  influxdbAdmin: "admin"
  fluentdImageRepository: index.docker.io
  fluentdImage: fluent/fluent-bit
  fluentdImageTag: 1.0.4
  
  ## Enable PodSecurityPolicies to allow privileged container
  ## Only required in some clusters and when enableSecurityContext is true
  podSecurityPolicy:
    enabled: false
   
    ## Configure additional capabilities
    additionalCapabilities:
    # example values for linkerd
    #- NET_RAW
    #- NET_ADMIN

  ## User can override resource limits/requests below
  resources: {}

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  ## Fluent-bit writes/reads it’s own sqlite database to record a history of tracked
  ## files and a state of offsets, this is very useful to resume a state if the ser-
  ## vice is restarted. For Kubernetes environment with constraints like OpenShift,
  ## the containers are limited to write hostPath volume. Hence, we have to enable
  ## security context and set privileged to true.  
  containerSecurityContext: {}
    # privileged: true

executor:
  adoptExistingResources: false

  ## User can override resource limits/requests below
  resources: {}

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}  

## Router config
router:
  deployAsDaemonSet: false
  svcAddressMaxRetries: 5
  svcAddressUpdateTimeout: 30s

  ## For minikube, set this to NodePort, elsewhere use LoadBalancer or ClusterIP.
  serviceType: LoadBalancer

  ## Used if the router is exposed via NodePort
  nodePort: 31314
  
  ## Display endpoint access logs
  ## To be aware of enabling logging endpoint access log, it increases
  ## router resource utilization when under heavy workloads.
  displayAccessLog: false
  
  ## Add annotations for router
  # svcAnnotations:
  #   cloud.google.com/load-balancer-type: Internal
  
  ## For router to match encoded path.
  ## If true, "/foo%2Fbar" will match the path "/{var}";
  ## Otherwise, it will match the path "/foo/bar".
  useEncodedPath: false
  
  roundTrip:
    ## If true, router will disable the HTTP keep-alive which result in performance degradation.
    ## But it ensures that router can redirect new coming requests to new function pods.
    ##
    ## If false, router will enable transport keep-alive feature for better performance.
    ## However, the drawback is it takes longer to switch to newly created function pods
    ## if using newdeploy as executor type for function. If you want to preserve the
    ## performance while keeping the short switching time to new function, you can create
    ## an environment with short grace period by setting flag "--graceperiod" (default 360s),
    ## so that kubernetes will be able to reap old function pod quickly.
    ##
    ## For details, see https://github.com/fission/fission/issues/723
    disableKeepAlive: false

    ## The keep-alive period for an active network connection to function pod.
    keepAliveTime: 30s

    ## HTTP transport request timeout
    timeout: 50ms

    ## The length of request timeout will multiply with timeoutExponent after each retry
    timeoutExponent: 2

    ## Max retries times of a failed request
    maxRetries: 10

  ## Sample with a rate per time window (traces/second)
  traceSamplingRate: 0.5

  ## User can override resource limits/requests below
  resources: {}

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}  

## Message queue trigger config
### NATS Streaming, enabled by default
nats:
  # whether or not to use NATS
  enabled: true

  ## Kubernetes configuration
  ## For minikube, set this to NodePort, elsewhere use LoadBalancer or ClusterIP.
  serviceType: ClusterIP`

  ## Port at which NATS Streaming service should be exposed when a nodePort service is used
  ## (only if nats enabled and not external)  
  nodePort: 31313

  # if true, don't install NATS, but
  external: false

  # Address of NATS server (domain:port)
  # change from default for external NATS
  hostaddress: 'nats-streaming:4222'

  # Authorization token to use with NATS
  authToken: "defaultFissionAuthToken"

  # NATS streaming clusterID
  clusterID: "fissionMQTrigger"

  # Client name registered with NATS streaming 
  clientID: "fission"

  # Queue group registered with NATS streaming 
  queueGroup: "fission-messageQueueNatsTrigger"

  # The image to use for NATS streaming server
  streamingserver:
    image: "nats-streaming:alpine"

  ## User can override resource limits/requests below
  resources: {}

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}  

mqtrigger:

  ## User can override resource limits/requests below
  resources: {}

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}  

storagesvc:

  ## User can override resource limits/requests below
  resources: {}

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}  

## Azure-storage-queue: enable and configure the details
azureStorageQueue:
  enabled: false
  key: ""
  accountName: ""
  
  ## User can override resource limits/requests below
  resources: {}   

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}  

## Kafka: enable and configure the details
kafka:
  enabled: false
  # note: below link is only for reference. 
  # Please use the brokers link for your kafka here. 
  brokers: 'broker.kafka:9092' # or your-bootstrap-server.kafka:9092/9093
  authentication:
    tls:
      enabled: false
      caCert: '' # path to certificate containing public key of CA authority
      userCert: '' # path to certificate containing public key of the user signed by CA authority
      userKey: '' # path to private key of the user

  # brokers: 'my-broker.kafka:9092' # or my-bootstrap-server.kafka:9092/9093
  # Sample config for authentication
  #   authentication:
  #   tls:
  #     enabled: true
  #     caCert: 'auth/kafka/ca.crt'
  #     userCert: 'auth/kafka/user.crt'
  #     userKey: 'auth/kafka/user.key'

  ## version of Kafka broker
  ## For 0.x it must be a string in the format
  ## "major.minor.veryMinor.patch" example: 0.8.2.0
  ## For 1.x it must be a string in the format
  ## "major.major.veryMinor" example: 2.0.1
  ## Should be >= 0.11.2.0 to enable Kafka record headers support
  # version: "0.11.2.0"

  ## User can override resource limits/requests below
  resources: {}     

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}  

## Persist data to a persistent volume.
persistence:
  ## If true, fission will create/use a Persistent Volume Claim
  ## If false, use emptyDir
  ##
  enabled: true

  ## A manually managed Persistent Volume Claim name
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  ##
  # existingClaim:

  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner. (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  accessMode: ReadWriteOnce
  size: 8Gi

## Extend the container specs for the core fission pods. 
## Can be used to add things like affinty/tolerations/nodeSelectors/etc.
## For example:
## extraCoreComponentPodConfig:
##   affinity:
##     nodeAffinity:
##       requiredDuringSchedulingIgnoredDuringExecution:
##         nodeSelectorTerms:
##           - matchExpressions:
##             - key: capability
##               operator: In
##               values:
##                 - app
#extraCoreComponentPodConfig:
#  affinity:
#  tolerations:
#  nodeSelector:

## Analytics let us count how many people installed fission. Set to
## false to disable analytics.
analytics: true

## Internally used for generating an analytics job for non-helm installs
analyticsNonHelmInstall: false

## Enable Heapster only in clusters where heapster does not exist already
heapster: false

## Enable InfluxDB
influxdb: 
  enabled: true
  image: influxdb:1.7

  ## User can override resource limits/requests below
  resources: {}

  ## User can override pod securityContext below
  podSecurityContext: {}

  ## User can override container securityContext below
  containerSecurityContext: {}  

## Enable fluentbit
fluentbit: true

# Allow user to override busybox image
busyboxImage: busybox

## Archive pruner is a garbage collector for archives on the fission storage service.
## This interval configures the frequency at which it runs inside the storagesvc pod.
## The value is in minutes.
pruneInterval: 60

# Allow user to disable pre-upgrade checks (in the event that something like Istio prevents any jobs from completing!)
preUpgradeChecks: true

## Fission pre-install/pre-upgrade checks live in this image
preUpgradeChecksImage: fission/pre-upgrade-checks

## if there are any pod specialization errors when a function is triggered and this flag is set to true, the error
## summary is returned as part of http response
debugEnv: false

## Prometheus for scrapping service metrics
prometheus:
  ## set this flag to true if prometheus needs to be deployed along with fission
  enabled: true
  
  ## If enabled is false, please assign the prometheus service URL
  ## that is accessible by components.
  serviceEndpoint: ""

## set this flag to false if you dont need canary deployment feature
canaryDeployment:
  enabled: true

# Use these flags to enable opentracing, the variable is endpoint of Jaeger collector in the format shown below
#traceCollectorEndpoint: "http://jaeger-collector.jaeger.svc:14268/api/traces?format=jaeger.thrift"
#traceSamplingRate: 0.75
