apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-{{ .Chart.Version }}-{{ randNumeric 3 }}
  labels:
    # The "release" convention makes it easy to tie a release to all of the
    # Kubernetes resources that were created as part of that release.
    release: "{{ .Release.Name }}"
    # This makes it easy to audit chart usage.
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        release: "{{ .Release.Name }}"
        app: {{ template "name" . }}
    spec:
      restartPolicy: Never
      containers:
      - name: pre-upgrade-job
        image: {{ .Values.preUpgradeChecksImage }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: ["/bin/bash", "-c"]
        args:
          - |
            trap "curl --max-time 2 -s -f -XPOST http://127.0.0.1:15000/quitquitquit" EXIT
            while ! curl -s -f http://127.0.0.1:15020/healthz/ready; do sleep 1; done
            sleep 2
            /pre-upgrade-checks --fn-pod-namespace {{ .Values.functionNamespace }} --envbuilder-namespace {{ .Values.builderNamespace }}
      serviceAccountName: fission-svc
