apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildermgr
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    svc: buildermgr
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: buildermgr
  template:
    metadata:
      labels:
        svc: buildermgr
{{- if .Values.builder.annotations }}
      annotations:
{{ toYaml .Values.builder.annotations | indent 8 }}  
{{ end }}         
    spec:
      securityContext:
{{ toYaml .Values.builder.podSecurityContext | indent 8 }}   
      volumes:
      - name: tmp
        emptyDir: {}      
      containers:
      - name: buildermgr
        image: {{ include "fission-bundleImage" . | quote }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: ["/fission-bundle"]
        args: ["--builderMgr", "--storageSvcUrl", "http://storagesvc.{{ .Release.Namespace }}", "--envbuilder-namespace", "{{ .Values.builderNamespace }}"]
        env:
        - name: FETCHER_IMAGE
          value: "{{ .Values.fetcher.image }}:{{ .Values.fetcher.imageTag }}"
        - name: FETCHER_IMAGE_PULL_POLICY
          value: "{{ .Values.pullPolicy }}"
        - name: BUILDER_IMAGE_PULL_POLICY
          value: "{{ .Values.pullPolicy }}"
        - name: ENABLE_ISTIO
          value: "{{ .Values.enableIstio }}"
        - name: TRACE_JAEGER_COLLECTOR_ENDPOINT
          value: "{{ .Values.traceCollectorEndpoint }}"
        - name: TRACING_SAMPLING_RATE
          value: {{ .Values.traceSamplingRate | default "0.5" | quote }}
        - name: FETCHER_MINCPU
          value: {{ .Values.fetcher.resources.cpu.requests | quote }}
        - name: FETCHER_MINMEM
          value: {{ .Values.fetcher.resources.mem.requests | quote }}
        - name: FETCHER_MAXCPU
          value: {{ .Values.fetcher.resources.cpu.limits | quote }}
        - name: FETCHER_MAXMEM
          value: {{ .Values.fetcher.resources.mem.limits | quote }}
        - name: DEBUG_ENV
          value: {{ .Values.debugEnv | quote }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
{{ toYaml .Values.builder.containerSecurityContext | indent 10 }}           
        resources:
{{ toYaml .Values.builder.resources | indent 10 }}
      serviceAccountName: fission-svc
{{- if .Values.extraCoreComponentPodConfig }}
{{ toYaml .Values.extraCoreComponentPodConfig | indent 6 -}}
{{- end }}