---
# Source: fission-all/templates/deployment.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: fission-builder
  labels:
    name: fission-builder
    chart: "fission-all-1.8.1-pre16"
---
# Source: fission-all/templates/deployment.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: fission-function
  labels:
    name: fission-function
    chart: "fission-all-1.8.1-pre16"
---
# Source: fission-all/templates/deployment.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-config
  namespace: default
data:
  "config.yaml": Y2FuYXJ5OgogIGVuYWJsZWQ6IHRydWUKICBwcm9tZXRoZXVzU3ZjOiAiaHR0cDovL1JFTEVBU0UtTkFNRS1wcm9tZXRoZXVzLXNlcnZlci5kZWZhdWx0Igo=
---
# Source: fission-all/templates/deployment.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-builder
  namespace: fission-builder
---
# Source: fission-all/templates/deployment.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-svc
  namespace: default
---
# Source: fission-all/templates/deployment.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-fetcher
  namespace: fission-function
---
# Source: fission-all/templates/deployment.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-configmap-getter
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - watch
  - list
---
# Source: fission-all/templates/deployment.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: package-getter
rules:
- apiGroups:
  - '*'
  resources:
  - packages
  verbs:
  - get
  - watch
  - list
---
# Source: fission-all/templates/deployment.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-crd
subjects:
- kind: ServiceAccount
  name: fission-svc
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# Source: fission-all/templates/deployment.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-admin
  namespace: default
subjects:
  - kind: ServiceAccount
    name: fission-svc
    namespace: default
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
# Source: fission-all/templates/deployment.yaml
#
# This is commented out until fission-ui allows configuring the
# namespace. Right now it just crashes if Release.Namespace !=
# "fission".
#
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: fission-ui
#  labels:
#    chart: "fission-all-1.8.1-pre16"
#spec:
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        svc: fission-ui
#    spec:
#      containers:
#      - name: nginx
#        image: index.docker.io/
#        imagePullPolicy: IfNotPresent
#      - name: kubectl-proxy
#        image: index.docker.io/lachlanevenson/k8s-kubectl
#        args: ["proxy", "--port", "8001", "--address", "127.0.0.1"]
#      serviceAccountName: fission-svc
