---
# Source: fission-all/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: storagesvc
  labels:
    svc: storagesvc
    application: fission-storage
    chart: "fission-all-1.8.1-pre16"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    svc: storagesvc
---
# Source: fission-all/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    svc: controller
    application: fission-api
    chart: "fission-all-1.8.1-pre16"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888
  selector:
    svc: controller
---
# Source: fission-all/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    svc: router
    application: fission-router
    chart: "fission-all-1.8.1-pre16"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8888
  selector:
    svc: router
---
# Source: fission-all/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: executor
  labels:
    svc: executor
    chart: "fission-all-1.8.1-pre16"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8888
  selector:
    svc: executor
---
# Source: fission-all/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: nats-streaming
  labels:
    svc: nats-streaming
    chart: "fission-all-1.8.1-pre16"
spec:
  type: ClusterIP`
  ports:
  - port: 4222
    targetPort: 4222
    name: tcp-nats-streaming
  selector:
    svc: nats-streaming
